import { FormEvent } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { EmptyState, ErrorState, LoadingState, StatusPill } from '../components/States'
import { useAsync } from '../hooks/useAsync'
import { api } from '../services/api'
import { Page } from './DashboardPage'

export function RunsPage() { const navigate = useNavigate(); const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); navigate(`/runs/${String(new FormData(event.currentTarget).get('run'))}`) }; return <Page><div className="page-title"><div><span className="eyebrow">Execution history</span><h1>Workflow runs</h1><p>Inspect a run directly by ID or open it after triggering a workflow.</p></div></div><form className="lookup" onSubmit={submit}><label>Run ID<input name="run" placeholder="e.g. 550e8400-e29b-41d4-a716-446655440000" required /></label><button className="button primary">Open run</button></form><EmptyState title="Run history is project-scoped" body="Use a workflow's Run action or enter a run ID above. Organization-wide history is planned for a later release." /></Page> }

export function RunDetailPage() { const { runId = '' } = useParams(); const run = useAsync(() => api.run(runId), [runId]); const logs = useAsync(() => api.logs(runId), [runId]); if (run.loading) return <Page><LoadingState label="Loading run" /></Page>; if (run.error) return <Page><ErrorState error={run.error} retry={run.reload} /></Page>; return <Page><Link className="back" to="/runs">← Runs</Link><div className="page-title"><div><span className="eyebrow">Run / {runId.slice(0, 8)}</span><h1>Workflow execution</h1><p>Created {run.data && new Date(run.data.createdAt).toLocaleString()}</p></div>{run.data && <StatusPill status={run.data.status} />}</div>{run.data?.error && <div className="inline-error">{run.data.error}</div>}<section className="panel"><div className="panel-head"><div><span className="eyebrow">Captured output</span><h2>Logs</h2></div></div>{logs.loading ? <LoadingState /> : logs.error ? <ErrorState error={logs.error} retry={logs.reload} /> : logs.data?.items.length ? <pre className="logs">{logs.data.items.join('')}</pre> : <EmptyState title="No logs yet" body="Logs appear after the worker starts executing steps." />}</section></Page> }
