import { FormEvent, useState } from 'react'
import { EmptyState, ErrorState, LoadingState } from '../components/States'
import { api } from '../services/api'
import { useAsync } from '../hooks/useAsync'
import { Page } from './DashboardPage'

export function SettingsPage() { const [saved, setSaved] = useState(false); const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); localStorage.setItem('forgeflow.organization', String(new FormData(event.currentTarget).get('organization'))); setSaved(true) }; return <Page><div className="page-title"><div><span className="eyebrow">Local preferences</span><h1>Settings</h1><p>Browser-only preferences never leave this device.</p></div></div><form className="form-card narrow-card" onSubmit={submit}>{saved && <div className="success" role="status">Settings saved.</div>}<label>Default organization ID<input name="organization" defaultValue={localStorage.getItem('forgeflow.organization') ?? ''} required /><small>Created with your account during registration.</small></label><button className="button primary">Save settings</button></form></Page> }
export function PluginsPage() { const plugins = useAsync(() => api.plugins(), []); return <Page><div className="page-title"><div><span className="eyebrow">Trusted extensions</span><h1>Plugins</h1><p>Compiled integrations for workflow steps, notifications, analytics, and repositories.</p></div></div>{plugins.loading ? <LoadingState /> : plugins.error ? <ErrorState error={plugins.error} retry={plugins.reload} /> : plugins.data?.items.length ? <div className="card-grid">{plugins.data.items.map(plugin => <article className="project-card" key={plugin.id}><span className="project-icon large">⬡</span><h2>{plugin.name}</h2><p>{plugin.description}</p><footer><code>{plugin.version}</code><span>{plugin.enabled ? 'Enabled' : 'Disabled'}</span></footer></article>)}</div> : <EmptyState title="No plugins enabled" body="The built-in run-summary example is available to developers. ForgeFlow intentionally does not load untrusted binaries at runtime." />}</Page> }
export function NotFoundPage() { return <Page><EmptyState title="Page not found" body="The route you requested does not exist." /></Page> }
